//products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

//alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//cart
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

//user
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_DETAILS = 'USER_DETAILS';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';
export const USER_DETAILS_ERROR = 'USER_DETAILS_ERROR';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';
export const USER_UPDATE_PROFILE_ERROR = 'USER_UPDATE_PROFILE_ERROR';
export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USERS_LIST_RESET = 'GET_USERS_LIST_RESET';
export const GET_USERS_LIST_ERROR = 'GET_USERS_LIST_ERROR';

//order
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_ERROR = 'ORDER_CREATE_ERROR';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const GET_ORDER_BY_ID_ERROR = 'GET_ORDER_BY_ID_ERROR';
export const UPDATE_ORDER_TO_PAID = 'UPDATE_ORDER_TO_PAID';
export const UPDATE_ORDER_TO_PAID_ERROR = 'UPDATE_ORDER_TO_PAID_ERROR';
export const UPDATE_ORDER_TO_PAID_RESET = 'UPDATE_ORDER_TO_PAID_RESET';
export const GET_MY_ORDER = 'GET_MY_ORDER';
export const GET_MY_ORDER_RESET = 'GET_MY_ORDER_RESET';
export const GET_MY_ORDER_ERROR = 'GET_MY_ORDER_ERROR';
